apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

android {
    signingConfigs {
        release {
            if (project.hasProperty("storeFile")) storeFile file("$rootDir/" + project.storeFile)
            if (project.hasProperty("storePassword")) storePassword project.storePassword
            if (project.hasProperty("keyAlias")) keyAlias project.keyAlias
            if (project.hasProperty("keyPassword")) keyPassword project.keyPassword
        }
    }
    compileSdk 37
    defaultConfig {
        applicationId "com.tomclaw.kvassword"
        minSdkVersion 21
        targetSdkVersion 37
        versionCode project.hasProperty("versionCode") ? Integer.parseInt(project.versionCode) : 100
        versionName "3.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig project.hasProperty("storeFile") ? signingConfigs.release : null
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        targetCompatibility 17
        sourceCompatibility 17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    namespace 'com.tomclaw.kvassword'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.github.solkin:bananalytics-android:v1.0.0'
}
